openapi: 3.0.3
info:
  version: '1.0'
  title: Fyler APIs
  termsOfService: 'https://www.fylehq.com/privacy/terms-and-conditions'
  contact:
    name: Integrations
    email: support@fylehq.com
servers:
  - url: 'https://platform.fylehq.com/v1'
    description: Testing Server
tags:
  - name: My Profile
    description: |
      This API gives you access to manage your profile data.
  - name: Expenses
    description: |
      This API gives you access to your Expenses data.
  - name: Expense Comments
    description: |
      This API gives you access to comment on a particular expense.
  - name: Expense Fields
    description: |
      This API gives you access to your organisation's Expense Fields data.
  - name: Reports
    description: |
      This API gives you access to your Expense Reports data.
  - name: Policy
    description: |
      These APIs handles the company wide policy operations.
  - name: Projects
    description: |
      These APIs gives you access to Projects data.
  - name: Cost Centers
    description: |
      These APIs gives you access to Cost Centers data.
  - name: Vendors
    description: |
      This API gives you a list of vendors
  - name: Categories
    description: |
      This API gives you list of your organisation's Categories data.
  - name: Currencies
    description: |
      This API gives you list of currencies supported by Fyle.
  - name: Exchange Rate
    description: |
      This API gives you exchange rate for a currency to a particular currency.
  - name: Expense Stats
    description: |
      This API gives you stats of your expenses.
  - name: Trip Requests Stats
    description: |
      This API gives you stats of your trip requests.
  - name: Advance Requests Stats
    description: |
      This API gives you stats of your advance requests.
  - name: Report Stats
    description: |
      This API gives you stats of your report.
  - name: Files
    description: |
      Creates a file.
  - name: Expense Files
    description: |
      Create a expense file.
  - name: Transportation Booking Files
    description: |
      Creates a transportation booking file.
  - name: Advance Request Files
    description: |
      Creates a advance request file.
  - name: Email Files
    description: |
      Creates a email file.
components:
  securitySchemes:
    oauth2:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: 'https://accounts.fylehq.com/app/developers/#/oauth/authorize'
          tokenUrl: 'https://accounts.fylehq.com/oauth/token'
  parameters:
    offset:
      in: query
      name: offset
      description: |
        Offset is used to skip that many number of objects before counting.
      schema:
        type: integer
        example: 10
    limit:
      in: query
      name: limit
      description: |
        A limit on the number of objects to be returned. Allowed values are from 1 to 200.
      schema:
        type: integer
        example: 100
        maximum: 200
        default: 50
    is_enabled:
      in: query
      name: is_enabled
      description: |
        This param is used to filter records.
        Supported operators are `eq`.<br>
      schema:
        type: string
        example: eq.true
    order:
      in: query
      name: order
      description: |
        use comma separated column names for sorting the results.
        For sorting in descending order, use `column_name.desc`
      schema:
        type: string
        example: 'updated_at.desc,id'
        default: 'updated_at.desc,id'
    created_at:
      in: query
      name: created_at
      description: |
        Date string in yyyy-MM-ddTHH:mm:ss.SSSZ format along with operator in RHS dot pattern.<br>
        Supported operators are `gte`,`lte`,`gt`,`lt`.<br>
        created_at=gte.2020-06-01T00:00:00.000Z filters all employees created on or after 1st Jun 2020.<br>
        created_at=gte.2020-06-01T00:00:00.000Z&created_at=lt.2020-07-01T00:00:00.000Z filters objects `created` in the month of Jun 2020.<br>
      schema:
        type: string
        example: 'gte.2020-06-01T00:00:00.000Z'
    updated_at:
      in: query
      name: updated_at
      description: |
        Date string in yyyy-MM-ddTHH:mm:ss.SSSZ format along with operator in RHS dot pattern.<br>
        Supported operators are `gte`,`lte`,`gt`,`lt`.<br>
        updated_at=gte.2020-06-01T00:00:00.000Z filters all employees updated on or after 1st Jun 2020.<br>
        updated_at=gte.2020-06-01T00:00:00.000Z&updated_at=lt.2020-07-01T00:00:00.000Z filters objects `updated` in the month of Jun 2020.<br>
      schema:
        type: string
        example: 'gte.2020-06-01T00:00:00.000Z'
  schemas:
    fields:
      id_str:
        type: string
        maxLength: 255
        description: |
          Identify the object
        readOnly: true
        example: '1'
      id_int:
        description: |
          Identify the object
        type: integer
        example: 1234
      count:
        description: |
          The total number of objects that can be requested.
        type: integer
        example: 10000
      offset:
        description: |
          offset is used to skip that many number of objects before counting. <br>
          For example, if there are 2000 objects, <br>
          The first request will have offset as 0 and limit as 1000 to return first 1000 objects. <br>
          The second request will have offset as 1000 and limit as 1000 to return next 1000 objects. <br>
        type: integer
        example: 10
      limit:
        description: |
          The actual number of objects that are returned in the response.
        type: integer
        example: 100
      created_at:
        type: string
        format: date-time
        description: |
          <a href="https://tools.ietf.org/html/rfc3339#section-5.6">RFC 3339, section 5.6 compliant timestamp.</a>
          Signifies when this object was created.
        readOnly: true
        example: '2020-06-01T13:14:54.804'
      org_id:
        type: string
        description: |
          The unique id of the Organization to which the object is associated.
        example: orNVthTo2Zyo
      updated_at:
        type: string
        format: date-time
        description: |
          <a href="https://tools.ietf.org/html/rfc3339#section-5.6">RFC 3339, section 5.6 compliant timestamp.</a>
          Signifies when this object was updated.
        readOnly: true
        example: '2020-06-11T13:14:55.201598'
    errors:
      '401':
        type: object
        properties:
          message:
            enum:
              - invalid token
            type: string
            description: |
              This error means that the input access token is either not issued by Fyle or has expired.
              You need to generate a new access token.
      '403':
        type: object
        properties:
          message:
            enum:
              - Forbidden
            type: string
            description: |
              This error means current user does not have enough permissions to perform this operation.
    cost_centers:
      out_single:
        type: object
        properties:
          id:
            type: string
            maxLength: 255
            description: |
              Identify the object
            readOnly: true
            example: '1'
          created_at:
            type: string
            format: date-time
            description: |
              <a href="https://tools.ietf.org/html/rfc3339#section-5.6">RFC 3339, section 5.6 compliant timestamp.</a>
              Signifies when this object was created.
            readOnly: true
            example: '2020-06-01T13:14:54.804'
          updated_at:
            type: string
            format: date-time
            description: |
              <a href="https://tools.ietf.org/html/rfc3339#section-5.6">RFC 3339, section 5.6 compliant timestamp.</a>
              Signifies when this object was updated.
            readOnly: true
            example: '2020-06-11T13:14:55.201598'
          org_id:
            type: string
            description: |
              The unique id of the Organization to which the object is associated.
            example: orNVthTo2Zyo
          name:
            type: string
            maxLength: 255
            description: |
              This represents the name of the cost center.
            example: sales & marketing
          code:
            type: string
            maxLength: 255
            description: |
              This represents the code of cost center.
            example: sm-cc
          description:
            type: string
            maxLength: 255
            description: |
              This field provides a decription about the cost center.
            example: Initial Cost center
          is_enabled:
            type: boolean
            description: |
              This field specifies if the current cost center is enabled or not.
            example: true
      out_many:
        type: object
        properties:
          count:
            description: |
              The total number of objects that can be requested.
            type: integer
            example: 10000
          offset:
            description: |
              offset is used to skip that many number of objects before counting. <br>
              For example, if there are 2000 objects, <br>
              The first request will have offset as 0 and limit as 1000 to return first 1000 objects. <br>
              The second request will have offset as 1000 and limit as 1000 to return next 1000 objects. <br>
            type: integer
            example: 10
          limit:
            description: |
              The actual number of objects that are returned in the response.
            type: integer
            example: 100
          url:
            type: string
            example: /fyler/cost_centers
          data:
            type: array
            items:
              type: object
              properties:
                id:
                  type: string
                  maxLength: 255
                  description: |
                    Identify the object
                  readOnly: true
                  example: '1'
                created_at:
                  type: string
                  format: date-time
                  description: |
                    <a href="https://tools.ietf.org/html/rfc3339#section-5.6">RFC 3339, section 5.6 compliant timestamp.</a>
                    Signifies when this object was created.
                  readOnly: true
                  example: '2020-06-01T13:14:54.804'
                updated_at:
                  type: string
                  format: date-time
                  description: |
                    <a href="https://tools.ietf.org/html/rfc3339#section-5.6">RFC 3339, section 5.6 compliant timestamp.</a>
                    Signifies when this object was updated.
                  readOnly: true
                  example: '2020-06-11T13:14:55.201598'
                org_id:
                  type: string
                  description: |
                    The unique id of the Organization to which the object is associated.
                  example: orNVthTo2Zyo
                name:
                  type: string
                  maxLength: 255
                  description: |
                    This represents the name of the cost center.
                  example: sales & marketing
                code:
                  type: string
                  maxLength: 255
                  description: |
                    This represents the code of cost center.
                  example: sm-cc
                description:
                  type: string
                  maxLength: 255
                  description: |
                    This field provides a decription about the cost center.
                  example: Initial Cost center
                is_enabled:
                  type: boolean
                  description: |
                    This field specifies if the current cost center is enabled or not.
                  example: true
paths:
  /fyler/cost_centers:
    get:
      tags:
        - Cost Centers
      summary: List cost centers
      operationId: get-cost-centers
      parameters:
        - in: query
          name: offset
          description: |
            Offset is used to skip that many number of objects before counting.
          schema:
            type: integer
            example: 10
        - in: query
          name: limit
          description: |
            A limit on the number of objects to be returned. Allowed values are from 1 to 200.
          schema:
            type: integer
            example: 100
            maximum: 200
            default: 50
        - in: query
          name: is_enabled
          description: |
            This param is used to filter records.
            Supported operators are `eq`.<br>
          schema:
            type: string
            example: eq.true
        - in: query
          name: order
          description: |
            use comma separated column names for sorting the results.
            For sorting in descending order, use `column_name.desc`
          schema:
            type: string
            example: 'updated_at.desc,id'
            default: 'updated_at.desc,id'
        - in: query
          name: created_at
          description: |
            Date string in yyyy-MM-ddTHH:mm:ss.SSSZ format along with operator in RHS dot pattern.<br>
            Supported operators are `gte`,`lte`,`gt`,`lt`.<br>
            created_at=gte.2020-06-01T00:00:00.000Z filters all employees created on or after 1st Jun 2020.<br>
            created_at=gte.2020-06-01T00:00:00.000Z&created_at=lt.2020-07-01T00:00:00.000Z filters objects `created` in the month of Jun 2020.<br>
          schema:
            type: string
            example: 'gte.2020-06-01T00:00:00.000Z'
        - in: query
          name: updated_at
          description: |
            Date string in yyyy-MM-ddTHH:mm:ss.SSSZ format along with operator in RHS dot pattern.<br>
            Supported operators are `gte`,`lte`,`gt`,`lt`.<br>
            updated_at=gte.2020-06-01T00:00:00.000Z filters all employees updated on or after 1st Jun 2020.<br>
            updated_at=gte.2020-06-01T00:00:00.000Z&updated_at=lt.2020-07-01T00:00:00.000Z filters objects `updated` in the month of Jun 2020.<br>
          schema:
            type: string
            example: 'gte.2020-06-01T00:00:00.000Z'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  count:
                    description: |
                      The total number of objects that can be requested.
                    type: integer
                    example: 10000
                  offset:
                    description: |
                      offset is used to skip that many number of objects before counting. <br>
                      For example, if there are 2000 objects, <br>
                      The first request will have offset as 0 and limit as 1000 to return first 1000 objects. <br>
                      The second request will have offset as 1000 and limit as 1000 to return next 1000 objects. <br>
                    type: integer
                    example: 10
                  limit:
                    description: |
                      The actual number of objects that are returned in the response.
                    type: integer
                    example: 100
                  url:
                    type: string
                    example: /fyler/cost_centers
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: string
                          maxLength: 255
                          description: |
                            Identify the object
                          readOnly: true
                          example: '1'
                        created_at:
                          type: string
                          format: date-time
                          description: |
                            <a href="https://tools.ietf.org/html/rfc3339#section-5.6">RFC 3339, section 5.6 compliant timestamp.</a>
                            Signifies when this object was created.
                          readOnly: true
                          example: '2020-06-01T13:14:54.804'
                        updated_at:
                          type: string
                          format: date-time
                          description: |
                            <a href="https://tools.ietf.org/html/rfc3339#section-5.6">RFC 3339, section 5.6 compliant timestamp.</a>
                            Signifies when this object was updated.
                          readOnly: true
                          example: '2020-06-11T13:14:55.201598'
                        org_id:
                          type: string
                          description: |
                            The unique id of the Organization to which the object is associated.
                          example: orNVthTo2Zyo
                        name:
                          type: string
                          maxLength: 255
                          description: |
                            This represents the name of the cost center.
                          example: sales & marketing
                        code:
                          type: string
                          maxLength: 255
                          description: |
                            This represents the code of cost center.
                          example: sm-cc
                        description:
                          type: string
                          maxLength: 255
                          description: |
                            This field provides a decription about the cost center.
                          example: Initial Cost center
                        is_enabled:
                          type: boolean
                          description: |
                            This field specifies if the current cost center is enabled or not.
                          example: true
        '401':
          type: object
          properties:
            message:
              enum:
                - invalid token
              type: string
              description: |
                This error means that the input access token is either not issued by Fyle or has expired.
                You need to generate a new access token.
