type: object
properties:
  name:
    type: string
    maxLength: 255
    description: Represents the name of the project.
    example: Fast and Furious
  sub_project:
    type: string
    maxLength: 255
    description: Represents the name of the sub_project.
    example: Formula One
  display_name:
    type: string
    maxLength: 513
    description: |
      This is a combination of name and sub_project separated by a / and spaces.
      In case if no sub_project is present it is same as name of the project.
    example: Fast and Furious / Formula One
  code:
    type: string
    maxLength: 255
    description: |
      This represents the code of project.
    example: FF-032
