type: object
readOnly: true
properties:
  id:
    type: string
    maxLength: 10
    example: '1234'
    description: |
      This id provided by Fyle to identify a project from this organisation.
      This id is a numeric string.
      This id is unique within the organisation.
  name:
    type: string
    maxLength: 255
    description: Represents the name of the project.
    example: Fast and Furious
  sub_project:
    type: string
    maxLength: 255
    description: Represents the name of the sub_project.
    example: Formula One
  display_name:
    type: string
    maxLength: 513
    description: |
      This is a combination of name and sub_project separated by a / and spaces.
      In case if no sub_project is present it is same as name of the project.
    example: Fast and Furious / Formula One
  code:
    type: string
    maxLength: 255
    description: |
      This represents the code of project.
    example: FF-032
