openapi: 3.0.3
info:
  version: '3.0'
  title: Fyle REST API
  contact:
    name: Integrations
    email: support@fyle.in
servers:
  - url: 'https://accounts.fylehq.com'
    description: Live Server

components:
  securitySchemes:
    oauth2:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: 'https://accounts.fylehq.com/app/developers/#/oauth/authorize'
          tokenUrl: 'https://accounts.fylehq.com/oauth/token'
          scopes:
            fyler.*: Grant all FYLER actions

tags:
  - name: Projects
    description: |
      These APIs gives you list of your organisation's Projects data.
  - name: Location
    description: |
      These APIs gives the location suggestions and geographic data of a place.

paths:
  /v4/fyler/projects:
    $ref: 'paths/projects.yaml'
  /v4/fyler/location_autocomplete:
    $ref: 'paths/location_autocomplete.yaml'
  /v4/fyler/location_geocode:
    $ref: 'paths/location_geocode.yaml'