openapi: 3.0.3
info:
  version: '3.0'
  title: Fyle REST API
  contact:
    name: Integrations
    email: support@fyle.in
servers:
  - url: 'https://accounts.fylehq.com'
    description: Live Server

components:
  securitySchemes:
    oauth2:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: 'https://accounts.fylehq.com/app/developers/#/oauth/authorize'
          tokenUrl: 'https://accounts.fylehq.com/oauth/token'
          scopes:
            fyler.*: Grant all FYLER actions

tags:
  - name: Projects
    description: |
      These APIs gives you list of your organisation's Projects data.
  - name: Expense Stats
    description: |
      This API gives you stats of your expenses.
  - name: Trip Requests Stats
    description: |
      This API gives you stats of your trip requests.
  - name: Advance Requests Stats
    description: |
      This API gives you stats of your advance requests.
  - name: Report Stats
    description: |
      This API gives you stats of your report.

paths:
  /v4/fyler/projects:
    $ref: 'paths/projects.yaml'
  /v4/fyler/expense_stats:
    $ref: 'paths/stats/expense.yaml'
  /v4/fyler/trip_requests_stats:
    $ref: 'paths/stats/trip_requests.yaml'
  /v4/fyler/advance_requests_stats:
    $ref: 'paths/stats/advance_requests.yaml'
  /v4/fyler/reports_stats:
    $ref: 'paths/stats/reports.yaml'
