openapi: 3.0.3
info:
  version: '3.0'
  title: Fyle REST API
  contact:
    name: Integrations
    email: support@fyle.in
servers:
  - url: 'https://accounts.fylehq.com'
    description: Live Server

components:
  securitySchemes:
    oauth2:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: 'https://accounts.fylehq.com/app/developers/#/oauth/authorize'
          tokenUrl: 'https://accounts.fylehq.com/oauth/token'
          scopes:
            fyler.*: Grant all FYLER actions

tags:
  - name: Projects
    description: |
      These APIs gives you list of your organisation's Projects data.
  - name: Vendors
    description: |
      This API gives you a list of vendors

paths:
  /v4/fyler/projects:
    $ref: 'paths/projects.yaml'
  /v4/fyler/vendors:
    $ref: 'paths/vendors.yaml'
  /v4/fyler/projects/{id}:
    $ref: 'paths/projects@{id}.yaml'
