openapi: 3.0.3
info:
  version: '1.0'
  title: Fyler APIs
  termsOfService: 'https://www.fylehq.com/privacy/terms-and-conditions'
  contact:
    name: Integrations
    email: support@fylehq.com
servers:
  - url: 'https://platform.fylehq.com/v1'
    description: Testing Server

components:
  securitySchemes:
    oauth2:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: 'https://accounts.fylehq.com/app/developers/#/oauth/authorize'
          tokenUrl: 'https://accounts.fylehq.com/oauth/token'

tags:
  - name: My Profile
    description: |
      This API gives you access to manage your profile data.
  - name: Expenses
    description: |
      This API gives you access to your Expenses data.
  - name: Expense Comments
    description: |
      This API gives you access to comment on a particular expense.
  - name: Expense Fields
    description: |
      This API gives you access to your organisation's Expense Fields data.
  - name: Reports
    description: |
      This API gives you access to your Expense Reports data.
  - name: Policy
    description: |
      These APIs handles the company wide policy operations.
  - name: Projects
    description: |
      These APIs gives you access to Projects data.
  - name: Cost Centers
    description: |
      These APIs gives you access to Cost Centers data.
  - name: Vendors
    description: |
      This API gives you a list of vendors
  - name: Categories
    description: |
      This API gives you list of your organisation's Categories data.
  - name: Currencies
    description: |
      This API gives you list of currencies supported by Fyle.
  - name: Exchange Rate
    description: |
      This API gives you exchange rate for a currency to a particular currency.
  - name: Expense Stats
    description: |
      This API gives you stats of your expenses.
  - name: Trip Requests Stats
    description: |
      This API gives you stats of your trip requests.
  - name: Advance Requests Stats
    description: |
      This API gives you stats of your advance requests.
  - name: Report Stats
    description: |
      This API gives you stats of your report.
  - name: Files
    description: |
      Creates a file.
  - name: Expense Files
    description: |
      Create a expense file.
  - name: Transportation Booking Files
    description: |
      Creates a transportation booking file.
  - name: Advance Request Files
    description: |
      Creates a advance request file.
  - name: Email Files
    description: |
      Creates a email file.

paths:
  /fyler/projects/{id}:
    $ref: 'paths/projects_id.yaml'
  /fyler/projects:
    $ref: 'paths/projects.yaml'
  /fyler/cost_centers/{id}:
    $ref: 'paths/cost_centers_id.yaml'
  /fyler/cost_centers:
    $ref: 'paths/cost_centers.yaml'
  /fyler/expenses/{id}:
    $ref: 'paths/expenses_id.yaml'
  /fyler/expenses:
    $ref: 'paths/expenses.yaml'
  /fyler/my_profile:
    $ref: 'paths/my_profile.yaml'
  /fyler/vendors:
    $ref: 'paths/vendors.yaml'
  /fyler/categories:
    $ref: 'paths/categories.yaml'
  /fyler/currencies:
    $ref: 'paths/currencies.yaml'
  /fyler/exchange_rate:
    $ref: 'paths/exchange_rate.yaml'
  /fyler/expense_stats:
    $ref: 'paths/stats/expense.yaml'
  /fyler/trip_requests_stats:
    $ref: 'paths/stats/trip_requests.yaml'
  /fyler/advance_requests_stats:
    $ref: 'paths/stats/advance_requests.yaml'
  /fyler/report_stats:
    $ref: 'paths/stats/reports.yaml'
  /fyler/expense_comments:
    $ref: 'paths/expense_comments.yaml'
  /fyler/expense_fields:
    $ref: 'paths/expense_fields.yaml'
  /fyler/policy_test:
    $ref: 'paths/policy_test.yaml'
  /fyler/reports:
    $ref: 'paths/reports.yaml'
  /fyler/files:
    $ref: 'paths/files/files.yaml'
  /fyler/expense_files:
    $ref: 'paths/files/expense.yaml'
  /fyler/transportation_booking_files:
    $ref: 'paths/files/transportation_booking.yaml'
  /fyler/advance_request_files:
    $ref: 'paths/files/advance_request.yaml'
  /fyler/email_files:
    $ref: 'paths/files/email.yaml'
